application: melinkeproj
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /.*
  static_files: home.html
  upload: home.html

- url: /.*
  script: handlers.app
